### PR TITLE
Remove unnecessary code & refactor code

### PR DESCRIPTION
**Pull request by Axorax**
Works properly as before but now the code is much cleaner and I also removed some unnecessary code in the index file (+page.svelte)

image

### CODE REVIEW

**Comment by JeremyGamer13** [comment]
this just seems like you ran an auto formatter on the whole repo with the wrong settings so the indenting size is wrong

**Comment by RedMan13** [comment]
> Works properly as before but now the code is much cleaner and I also removed some unnecessary code in the index file (+page.svelte)
> 
> image

what "unecesary code" was removed....

**Comment by RedMan13** [comment]
ok so there is ALOT wrong with this commit (including the fact that it doesnt seem to remove any code :trollface:)

- while i understand that the current home page code may look like garbag (and performs like it too) that is at the fault of the way it is made not the formating of the code
- two-space tab width reads horribly compared to four-space tab width
- isnt it "DOCTYPE" and not "doctype"?
- a minor nitpick of mine is the usage of `"` instead of `'`, wich just kinda looks wrong
- another nitpick is the replacement of `*` inside of the markdown files
- having a trailing `,` on objects just looks bad and having inconsistent quotes around value names in objects looks ugly, including when no keys in the object require it and there added anyways
- removing whitespace that aligns two separate columns of information is just bad and unhelpfull
- lowercase hexcodes look bad

that is my heavily opinionated assessment of this commit
TL,DR exactly what jeremy said :trollface:

**Comment by RedMan13** [comment]
> " superiority!!!! ' bad!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

but its look like bad kinda old and more keystrokes to type :grr

**Pull request closed without merging**
