### PR TITLE
Custom Scratch Auth Frontend

### LINKED ISSUE #20: Utilize a Different Scratch Auth Frontend.
Hey! I'm aware of this project's relative popularity in the Scratch modding space. I'm also aware that PenguinMod uses the default provided front-end of Scratch Auth for authentication. This, on it's own, is not a problem. What is a problem, however, is that people frequently spam the comments section of Looky(the creator, owner, and primary-maintainer of Scratch Auth) with comments relating to issues they face while using PenguinMod.

I don't think anyone should be spammed, I hope you agree with me. Which is why I'm requesting that you stop using the unmodified front-end of Scratch Auth without changing it to make it clear that this project is not affiliated with Scratch Auth.

**What Do I Mean By "Front-End"**

Scratch Auth works with it's own backend API, an API that just happens to have CORs enabled, meaning it can be accessed from anywhere by both JS code, and _backend_ JS code. It's API is pretty ok-ly documented, although you have to do some digging. I already did this digging.

* **GET** https://auth.itinerary.eu.org/api/auth/getTokens
  _Query Options:_
  **redirect**\* - String ( base64 encoded url )
  method - Enum ( "cloud", "comment" )
  authProject - String ( ID of the Scratch project used for authentication )
* **GET** https://auth.itinerary.eu.org/api/auth/verifyTokens/:privateCode
  _Query Parameters:_
  **privateCode**\* - String ( private code given by `getTokens` )
  _Query Options:_
  **redirect**\* - String ( base64 encoded url, only required when `oneClickSignIn` is true )
  oneClickSignIn - Boolean
* **GET** https://auth.itinerary.eu.org/api/auth/oneClickSignIn
  _Headers:_
  **Authorization**\* - String
* **POST** https://auth.itinerary.eu.org/api/auth/oneClickSignIn/:username
  _Headers:_
  **Authorization**\* - String
  _Query Parameters:_
  **username**\* - String
  _Query Options:_
  **redirect** - String ( base64 encoded url )
* **DELETE** https://auth.itinerary.eu.org/api/auth/oneClickSignIn/:username
  _Headers:_
  **Authorization**\* - String
  _Query Parameters:_
  **username**\* - String

\* = required

Based off of [this image](https://user-images.githubusercontent.com/75220768/263859666-722bb72d-7f54-445c-bf7b-f28e3cf5c6fb.png) of a forum post on the original Scratch Auth Forum Topic(before it got dustbinned).

### PR DESCRIPTION
**Pull request by Steve0Greatness**
Resolves #20.

**Issues**

* There is _no one click sign in_. Due to authentication being done on the backend, one click would need to partially be implemented in the backend. However, if somebody does end up editing that nightmare of a codebase, then there's some code with (basic) documentation.
* It could be controversial. Many people in the Discord server seemed unhappy about how it looked.
  * This was due to it looking bland(which I agree with).

Also, just a quick note: I haven't been able to get it to work on development servers, however from what I can tell it's about as close to a drag-and-drop replacement to Scratch Auth as I can get it, so IDK what's up with that.

### CODE REVIEW

**Comment by Steve0Greatness** [comment]
Wait, I don't know what's happening here. I'm gonna close this until I get this issue fixed.

**Comment by Steve0Greatness** [comment]
It's not fixed, I have no clue what's happening.

**Comment by Steve0Greatness** [comment]
The bug _should_ be fixed.

**Comment by Steve0Greatness** [comment]
Okay, I just realized something.

**Comment by Steve0Greatness** [comment]
Scratch Auth does something called "Cleanups," which is when it clears tokens and one-click accounts that aren't valid anymore. It does this every hour. While in the cleanup state, Scratch Auth cannot generate or validate tokens.

I don't know if this is the root the problem with people having trouble logging in every-so-often, but it probably is.

**Comment by Steve0Greatness** [comment]
Cloud Authentication is back now. Should I re-enable cloud authentication?

**Comment by JeremyGamer13** [comment]
in the process of being superceded by new-backend-integration, but since this was a project for a while & can still serve as a base for something else in the future, ill still credit you & probably use some parts from it

will close once its in prod

**Comment by JeremyGamer13** [comment]
new sign in is in prod now
sorry for not using this we were just told about scratch wiki being possibly more reliable

**Pull request closed without merging**
