### PR TITLE
pretty numbers on the vote embed :)

### PR DESCRIPTION
**Pull request by PuzzlingGGG**
that’s it… it just formats numbers so like 4000 will be 4,000 soooo yeah

### CODE REVIEW

**Comment by PuzzlingGGG** [comment]
wait it didn't work what

**Comment by PuzzlingGGG** [comment]
ohhh nvm hold up don't merge yet

**Comment by PuzzlingGGG** [comment]
Bro why isn't it working nvm 😭

**Comment by NotEmbin** [comment]
noooo 😢

**Comment by Ianyourgod** [comment]
why tf are you using regex

**Comment by PuzzlingGGG** [comment]
idk

**Pull request closed without merging**
