### PR TITLE
Update Tips.json

### PR DESCRIPTION
**Pull request by RedMan13**

### CODE REVIEW

**Comment by derpygamer2142** [comment]
yo can a pm admin check why it failed, it gives me a 404

**Comment by JeremyGamer13** [comment]
image

**Comment by JeremyGamer13** [comment]
also some of these made my updated tips be outdated again lol

**Comment by RedMan13** [comment]
> image

well thats not very helpfull

**Comment by derpygamer2142** [comment]
doot doot

**Review by derpygamer2142 — APPROVED** [review]
uh i think this will say its done but idk

**Comment by RedMan13** [comment]
merged

**Pull request closed without merging**
