### PR TITLE
ok hopefully the last pull request for this stupid tip

### PR DESCRIPTION
**Pull request by ilikecoding-197**
should be it.... hopefully

### CODE REVIEW

**Comment by ilikecoding-197** [comment]
oh when I tried to click he edit button it didn't work. I'm also very new to github.

**Comment by RedMan13** [comment]
you need to do it in your fork outside a commit preview

**Comment by RedMan13** [comment]
because of the way importing works im pretty sure that will just keep readding that specific element to the tips list

**Comment by RedMan13** [comment]
> no? its not a mutible thing, its not gonna update that json file, that would be very strange behavior

but that's not how the compile works? unless it's saving the file literally and reparsing it on every reference or it's actually freezing the object, the cached parse will be innately mutable and have that mutation accessable by all other instances

although this fact can not cross pages so it's a warning not an issue as I had originally thought (as it can only be an issue in places where multiple tips are being shown on the same page, regardless of timing)

**Pull request merged**
