### PR TITLE
update nav bar to use title ATTRIBUITE

### PR DESCRIPTION
**Pull request by NexusKitten**
this way, you can see what a button does by hovering over it

### CODE REVIEW

**Comment by RedMan13** [comment]
didnt realize title was an event

**Comment by NexusKitten** [comment]
> didnt realize title was an event

minor spelling mistake i lose

**Comment by RedMan13** [comment]
thankfully vercel makes builds of prs

**Comment by RedMan13** [comment]
why did you reformat everything to use tab characters :sob:

**Comment by RedMan13** [comment]
also i dont see any titles when i view the previue so like :trollface:

**Comment by NexusKitten** [comment]
> why did you reformat everything to use tab characters 😭

I did? that might have been a vscode thing because i didn't touch most of the code

**Comment by NexusKitten** [comment]
> also i dont see any titles when i view the previue so like :trollface:

hover over the icons (specifically the ones without text)

**Comment by RedMan13** [comment]
> > also i dont see any titles when i view the previue so like :trollface:
> 
> hover over the icons (specifically the ones without text)

 mmmmno i did tht and nothing happrened

**Comment by NexusKitten** [comment]
Photos_mtQ5NvHUKw

**Comment by RedMan13** [comment]
oh cause itd nitthe [m logo that has it

**Pull request merged**
