### PR TITLE
Move over the TOS & Privacy Policy

### LINKED ISSUE #49: Move the terms.html and privacy.html from studio.PenguinMod to here.
I don't believe I need much more of an explanation for this. Also, about previous links being broken, you can place this code(below) as the content for the previous HTML content(just make sure to replace the ... with the path to the new route).

```
<meta http-equiv="refresh" content="0; URL='https://penguinmod.com/...'" />
```

This would introduce more consistency in URLs. Also, having the header on these pages would be nice as well.

### PR DESCRIPTION
**Pull request by Steve0Greatness**
Resolves #49 

This PR moves over `terms.html` and `privacy.html` from [PenguinMod/penguinmod.github.io](https://github.com/PenguinMod/penguinmod.github.io), as well as adding the header and replacing the heading of these pages with `div.section-info`s.

### CODE REVIEW

**Comment by JeremyGamer13** [comment]
i wont make this happen in this pull request (because its really annoying) but we should eventually make these into markdown files like the uploading guidelines so they are easily editable

**Comment by Steve0Greatness** [comment]
> i wont make this happen in this pull request (because its really annoying) but we should eventually make these into markdown files like the uploading guidelines so they are easily editable & possibly translatable

Alright, would they be under the guidelines paths? Or have their own paths like here?

**Comment by JeremyGamer13** [comment]
the guidelines page was made in a way that would make it easy to add another page for guidelines on another part of penguinmod, but TOS and Privacy probably dont need that so i would just put the md files in the folder with the svelte page & probably add some way for the pages to use a different file if the language is different

**Comment by Steve0Greatness** [comment]
Alright then, I'll revise this branch. Thanks for the clarification!

**Comment by Steve0Greatness** [comment]
Oh... this got merged. I forgot that purple meant that it was merged.

**Pull request merged**
